### PR TITLE
Mp customer controller

### PR DESCRIPTION
**Pull request by MissPeperr**
## Link to Ticket
_almost_ Closes # [Customer Resource](https://github.com/NSS-Wacky-Eels/BangazonAPI/issues/2)

## Description of Proposed Changes

Finished basic CRUD operations according to ticket.
User can also filter for a specific customer in the URL 

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout <MP-CustomerController>

```
Then test all CRUD operations (except delete)

## Impacted Areas in Application

List general components of the application that this PR will affect:

* Customer Component

## Mentions @username

Tag users that need to review this code

## Definition of Done

1. The project must be fully documented. This includes the following:
    a. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    b. Every class must be documented with purpose, author, and methods.
    c. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
2. The project must be able to run fully, and without errors, on each teammate's system.
3. Fulfills every requirement.
Every line of code has been peer reviewed.
4. For projects that require unit testing, core functionality must be identified and have at least one test for each.

### CODE REVIEW

**Review by mateusvanhalen — APPROVED** [review]
I see no remaining students :). Great

**Review by streatorward — APPROVED** [review]
All actions work to me!

**Comment by megducharme** [comment]
What is the "almost"? Is there something else you wanted to add? This *technically* doesn't meet the definition of done because it's not commented out, but that's ok for now. We will show you how to do that soon!

**Review by megducharme — APPROVED** [review]
LGTM! (looks good to me!) 🔥

**Pull request merged**
